-- Table `creature_template` lists creature (Entry: 190011) with disallowed `flags_extra` 8388608, removing incorrect flag.
UPDATE `creature_template` SET `flags_extra`= 0 WHERE `entry` IN (190011,190013);

-- Creature (Entry: 19719) cant`t has oneshot emote 14 in `creature_template_addon` field, you should use scripts, skipped.
UPDATE `creature_template_addon` SET `emote`= 0 WHERE `entry` IN (19719,64249);

-- Creature (GUID 6348) has movement type set to WAYPOINT_MOTION_TYPE but no path assigned
UPDATE `creature` SET `movement_type`= 0 WHERE `guid` IN (6348,6350,92307);

-- Creature (GUID: 87329) has wrong spell 0 defined in `auras` field in `creature_addon`.
UPDATE `creature_addon` SET `auras`= '29266' WHERE `guid` IN (87328,87329);

-- Weekly Quest 31539 not marked as repeatable in `SpecialFlags`, added.
UPDATE `quest_template` SET `SpecialFlags`= 1 WHERE `Id` = 31539;

-- SmartWaypointMgr::LoadFromDB: Path entry 64249, unexpected point id 0, expected 1.
DELETE FROM `waypoints` WHERE `entry`=64249;
INSERT INTO `waypoints` (`entry`, `pointid`, `position_x`, `position_y`, `position_z`, `orientation`, `delay`, `point_comment`) VALUES 
(64249, 1, 532.575, -1668.05, 203.688, NULL, 0, NULL),
(64249, 2, 709.89, -1785.65, 203.688, NULL, 0, NULL),
(64249, 3, 776.472, -1776.76, 158.677, NULL, 0, NULL),
(64249, 4, 908.051, -1804.16, 158.677, NULL, 0, NULL),
(64249, 5, 931.47, -1868.49, 158.677, NULL, 0, NULL),
(64249, 6, 903.01, -1954.38, 158.677, NULL, 0, NULL),
(64249, 7, 768.653, -1934.81, 168.677, NULL, 0, NULL),
(64249, 8, 598.673, -1726.35, 212.529, NULL, 0, NULL),
(64249, 9, 533.371, -1670.25, 202.78, NULL, 0, NULL);

UPDATE `smart_scripts` SET `event_param1`= 9 WHERE `entryorguid`= 64249 AND `source_type`= 0 AND `id`= 1 AND `event_param1`= 8;

-- Scriptname: `spell_ataldazar_pursuit` spell (Id: 257407) does not exist.
DELETE FROM `spell_script_names` WHERE `ScriptName` IN (
'spell_warl_soul_shards_visual_test',
'spell_warl_demonic_fury_visual_controller',
'spell_pal_glyph_of_bladed_judgement',
'spell_ataldazar_soulrend_selector',
'spell_ataldazar_echoes_of_shadra_selector',
'spell_ataldazar_fiery_enchant_selector',
'spell_ataldazar_pursuit');

-- ScriptName '85084spell_howling_gale_howling_gale' exists in database, but no core script found!
UPDATE `spell_script_names` SET `ScriptName`= 'spell_howling_gale_howling_gale' WHERE `ScriptName` = '85084spell_howling_gale_howling_gale';

-- ScriptName 'achievement_im_on_a_boat' exists in database, but no core script found!
UPDATE `achievement_criteria_data` SET `ScriptName`= '' WHERE `ScriptName` IN (
-- ScriptName 'achievement_ohganot_so_fast' exists in database, but no core script found!
'achievement_ohganot_so_fast',
'achievement_on_the_rocks',
'achievement_pardon_denied',
'achievement_shatter_resistant');

-- ScriptName 'at_alizabal_intro' exists in database, but no core script found!
DELETE FROM `areatrigger_scripts` WHERE `ScriptName` IN (
-- ScriptName 'at_well_of_eternity_skip_illidan_intro' exists in database, but no core script found!
'at_alizabal_intro',
'at_bt_sinestra',
'at_eye_of_eternity_improvised_floor',
'at_hor_intro_start',
'at_madrigosa',
'at_svala_intro',
'at_twiggy_flathead',
'at_twilight_grove');

-- ScriptName 'npcs_dithers_and_arbington' exists in database, but no core script found!
UPDATE `creature_template` SET `ScriptName`= '' WHERE `ScriptName` IN (
'npc_afd_royale_controller',
'npc_afd_royale_ring',
'spell_ex_49375',
'boss_arcanist_doan',
'boss_arlokk',
'boss_azshir_the_sleepless',
'boss_bloodmage_thalnos',
'boss_boss_ras_frostwhisper',
'boss_darkmaster_gandling',
'boss_death_knight_darkreaver',
'boss_doctor_theolen_krastinov',
'boss_fenstalker',
'boss_gahzranka',
'boss_glutton',
'boss_hakkar',
'boss_herod',
'boss_high_inquisitor_fairbanks',
'boss_houndmaster_loksey',
'boss_illucia_barov',
'boss_instructor_malicia',
'boss_interrogator_vishas',
'boss_jeklik',
'boss_jindo',
'boss_kirtonos_the_herald',
'boss_koragg',
'boss_kormok',
'boss_lord_alexei_barov',
'boss_lord_raadan',
'boss_lorekeeper_polkelt',
'boss_marli',
'boss_mordresh_fire_eye',
'boss_mr_smite',
'boss_protectors_of_the_endless',
'boss_scarlet_commander_mograine',
'boss_scorn',
'boss_the_ravenian',
'boss_thekal',
'boss_thurg',
'boss_trial_of_king',
'boss_tuten_kash',
'boss_twilight_corrupter',
'boss_vectus',
'generic_creature',
'generic_vehicleAI_toc5',
'gerenic_creature',
'npc_agnetta_tyrsdottar',
'npc_anachronos_15192',
'npc_anachronos_quest_trigger',
'npc_anachronos_the_ancient',
'npc_anchorite_truuen',
'npc_andorhal_tower',
'npc_aran_blizzard',
'npc_arugal_voidwalker',
'npc_ashtongue_defender',
'npc_ashtongue_elementalist',
'npc_ashtongue_rogue',
'npc_ashtongue_spiritbinder',
'npc_bartleby',
'npc_batrider',
'npc_belnistrasz',
'npc_blaze',
'npc_blazing_monstrosity',
'npc_bloodmaul_brute',
'npc_blue_dragon_53394',
'npc_brann_bronzebeard_keystone',
'npc_brewfest_apple_trigger',
'npc_brewfest_ram_master',
'npc_brewfest_trigger',
'npc_broggok_poison_cloud',
'npc_burning_cupboard',
'npc_cairne_bloodhoof',
'npc_calvin_montague',
'npc_cave_in_stalker',
'npc_chains_of_woe',
'npc_clintar_spirit',
'npc_commander_eligor_dawnbringer',
'npc_corporal_keeshan',
'npc_crazed_colossus',
'npc_creature_generator_akama',
'npc_crystal_spike_trigger',
'npc_dark_iron_guzzler',
'npc_demon_fire',
'npc_egg_pile',
'npc_flame_crash',
'npc_flarecore_golem',
'npc_galen_goodward',
'npc_generic_harpoon_cannon',
'npc_great_bear_spirit',
'npc_greenstone_belligerent_blossom',
'npc_hallegosa',
'npc_harbinger_of_flame',
'npc_harrison_jones',
'npc_healing_ward',
'npc_homunculus',
'npc_idol_room_spawner',
'npc_imp_in_a_ball',
'npc_invis_legion_teleporter',
'npc_jikun_teleport',
'npc_kalecgos_53149',
'npc_kalecgos_53349',
'npc_kalecgos_53392',
'npc_king_jokkum_vehicle',
'npc_krikthik_glider',
'npc_lady_katrana_prestor',
'npc_lord_gregor_lescovar',
'npc_lord_hiram_creed',
'npc_mandokir_ohgan',
'npc_marzon_silent_blade',
'npc_mikhail',
'npc_mindless_abomination',
'npc_mindless_skeleton',
'npc_molten_barrage',
'npc_mostrasz_56314',
'npc_mountaineer_pebblebitty',
'npc_myranda_the_hag',
'npc_nether_vapor',
'npc_omega_stance',
'npc_oscillating_frequency_scanner_master_bunny',
'npc_pri_divine_star',
'npc_pulsing_pumpkin',
'npc_qiraj_war_spawn',
'npc_ragged_john',
'npc_rinji',
'npc_scarlet_trainee',
'npc_scourge_hulk',
'npc_searing_gaze',
'npc_shade_of_jindo',
'npc_shadowfang_prisoner',
'npc_silva_filnaveth',
'npc_sliver',
'npc_solo_queue',
'npc_spawn_of_marli',
'npc_spectator',
'npc_stalker_53422',
'npc_tapoke_slim_jahn',
'npc_tarecgosa_53098',
'npc_tarecgosa_53396',
'npc_the_etymidian',
'npc_the_scourge_cauldron',
'npc_thuzadin_acolyte',
'npc_thyrinar',
'npc_torturer_leCraft',
'npc_toy_mini_maba_bomb',
'npc_tracy_proudwell',
'npc_trainee_stifled_pride',
'npc_tribunal_of_ages',
'npc_tvs_black_prince',
'npc_tyrion',
'npc_tyrion_spybot',
'npc_vilebranch_speaker',
'npc_voljin_zulaman',
'npc_wisp_invis',
'npc_wrathbone_flayer',
'npc_wrathion_57777',
'npc_yauj_brood',
'npc_zealot_lorkhan',
'npc_zealot_zath',
'npc_zulaman_hostage',
'npc_zulian_prowler',
'npcs_dithers_and_arbington',
'pyrewood_ambush',
'sat_icy_shadows',
'shang_xi_air_balloon');

-- ScriptName 'go_abandoned_mole_machine' exists in database, but no core script found!
UPDATE `gameobject_template` SET `ScriptName`= '' WHERE `ScriptName` IN (
'go_abandoned_mole_machine',
'go_atalai_statue',
'go_brazier_of_the_herald',
'go_crystalline_tear',
'go_door_lever_dm',
'go_dungeon_archaeology_quest',
'go_gong_of_bethekk',
'go_iruxos',
'go_kael_orb',
'go_loosely_turned_soil',
'go_mausoleum_door',
'go_mausoleum_trigger',
'go_mole_machine_console',
'go_movie_orb',
'go_panther_cage',
'go_rattlegore_iron_door');

-- ScriptName 'item_brewfest_ChugAndChuck' exists in database, but no core script found!
DELETE FROM `item_script_names` WHERE `ScriptName` IN (
'item_brewfest_ChugAndChuck',
'item_brewfest_ram_reins',
'item_charging_decorder_ring',
'item_defias_gunpowder',
'item_isengard_bonus_reward');

-- ScriptName 'spell_ahn_kahet_swarm' exists in database, but no core script found!
DELETE FROM `spell_script_names` WHERE `ScriptName` IN (
'spell_afd_royale_buff_trigger',
'spell_afd_royale_drop',
'spell_afd_royale_in_map',
'spell_afd_royale_leaving_game',
'spell_afd_royale_out_of_ring_damage_aura',
'spell_afd_royale_portal_trigger',
'high_priestess_azil_gravity_well_script',
'spell_ahn_kahet_swarm',
'spell_alysrazor_aggro_closest',
'spell_alysrazor_cosmetic_egg_xplosion',
'spell_alysrazor_turn_monstrosity',
'spell_anhuur_activate_beacons',
'spell_anhuur_disable_beacon_beams',
'spell_anhuur_divine_reckoning',
'spell_anhuur_shield_of_light',
'spell_anraphet_alpha_beams',
'spell_anraphet_omega_stance_summon',
'spell_anshal_nurture_summon_trigger',
'spell_assembly_rune_of_summoning',
'spell_ataldazar_echoes_of_shadra_selector',
'spell_ataldazar_fiery_enchant_selector',
'spell_ataldazar_pursuit',
'spell_ataldazar_soulrend_selector',
'spell_auriaya_strenght_of_the_pack',
'spell_banging_the_gong',
'spell_barrel_periodic',
'spell_bg_arena_dampening',
'spell_blood_queen_essence_of_the_blood_queen',
'spell_brewfest_speed',
'spell_broggok_poison_cloud',
'spell_crossfaction_bg_set_faction_a',
'spell_crossfaction_bg_set_faction_h',
'spell_crystal_spike',
'spell_cultist_dark_martyrdom',
'spell_cultist_dark_martyrdrom',
'spell_devourer_of_souls_mirrored_soul',
'spell_devourer_of_souls_mirrored_soul_proc',
'spell_devourer_of_souls_mirrored_soul_target_selector',
'spell_dk_blood_gorged',
'spell_dk_dark_transformation_form',
'spell_dk_death_strike_enabler',
'spell_dk_icebound_fortitude',
'spell_dk_improved_blood_presence',
'spell_dk_rune_tap_party',
'spell_dk_scent_of_blood',
'spell_dk_unholy_presence',
'spell_dru_enrage',
'spell_dru_glyph_of_starfire_proc',
'spell_dru_insect_swarm',
'spell_dru_natures_cure',
'spell_dru_rip',
'spell_dru_solar_beam',
'spell_dru_soul_of_the_forest_eclipse',
'spell_dru_typhoon',
'spell_dru_ursols_vortex',
'spell_dru_ursols_vortex_snare',
'spell_earthrager_ptah_explosion',
'spell_earthrager_ptah_flame_bolt',
'spell_elder_nadox_guardian',
'spell_ex_absorb_aura',
'spell_fixate',
'spell_flying_kick',
'spell_frost_tomb',
'spell_gathered_storms_trigger_cast',
'spell_gen_dark_iron_dwarf_spawn',
'spell_gen_dark_iron_knockback_test',
'spell_gen_demon_hunters_aspect',
'spell_gen_eject_all_passengers',
'spell_gen_gm_freeze',
'spell_gen_gunship_portal',
'spell_gen_nightmare_vine',
'spell_gen_parachute_ic',
'spell_gen_remove_aura_on_remove_blades_of_renataki',
'spell_gen_remove_aura_on_remove_wushoolays_lightning',
'spell_gen_ribbon_pole_dancer_check',
'spell_gen_singing_sunflower',
'spell_gen_throw_shield',
'spell_general_vezax_mark_of_the_faceless',
'spell_general_vezax_mark_of_the_faceless_leech',
'spell_general_vezax_saronite_vapors',
'spell_gilneas_quest_save_the_children',
'spell_gordunni_trap',
'spell_grobbulus_mutating_injection',
'spell_grobbulus_poison_cloud',
'spell_hor_evasion',
'spell_hor_start_halls_of_reflection_quest_ae',
'spell_hun_blink_strike',
'spell_hun_rapid_fire',
'spell_hun_readiness',
'spell_hun_viper_attack_speed',
'spell_hunt_steady_shot',
'spell_igb_below_zero',
'spell_igb_burning_pitch',
'spell_igb_burning_pitch_selector',
'spell_igb_cannon_blast',
'spell_igb_check_for_players',
'spell_igb_gunship_fall_teleport',
'spell_igb_incinerating_blast',
'spell_igb_on_gunship_deck',
'spell_igb_overheat',
'spell_igb_periodic_trigger_with_power_cost',
'spell_igb_rocket_artillery',
'spell_igb_rocket_artillery_explosion',
'spell_igb_rocket_pack',
'spell_igb_rocket_pack_useable',
'spell_igb_teleport_players_on_victory',
'spell_igb_teleport_to_enemy_ship',
'spell_ingvar_summon_banshee',
'spell_ingvar_woe_strike',
'spell_item_bad_juju',
'spell_item_stay_of_execution',
'spell_jokkum_scriptcast',
'spell_koegler_fireball_valley',
'spell_kormok_summon_bone_mages',
'spell_kormok_summon_bone_minions',
'spell_light_of_blades',
'spell_load_into_catapult',
'spell_loken_pulsing_shockwave',
'spell_lord_victor_nefarius_shadow_infusion',
'spell_mage_blast_wave',
'spell_mage_cone_of_cold',
'spell_mage_frost_bomb_cooldown_reduction',
'spell_mage_glyph_of_fire_blast',
'spell_mage_ice_barrier',
'spell_mage_invocation',
'spell_mage_polymorph_visual',
'spell_mage_replenish_mana',
'spell_mandokir_devastating_slam_damage',
'spell_marwyn_shared_suffering',
'spell_mastery_hand_of_light',
'spell_mastery_icicles',
'spell_mastery_ignite',
'spell_mimiron_bomb_bot',
'spell_mimiron_clear_fires',
'spell_mimiron_despawn_assault_bots',
'spell_mimiron_fire_search',
'spell_mimiron_flame_suppressant',
'spell_mimiron_magnetic_core',
'spell_mimiron_napalm_shell',
'spell_mimiron_p3wx2_laser_barrage',
'spell_mimiron_plasma_blast',
'spell_mimiron_proximity_explosion',
'spell_mimiron_proximity_mines',
'spell_mimiron_proximity_trigger',
'spell_mimiron_rapid_burst',
'spell_mimiron_rocket_strike',
'spell_mimiron_rocket_strike_damage',
'spell_mimiron_rocket_strike_target_select',
'spell_mimiron_self_repair',
'spell_mimiron_spinning_up',
'spell_mimiron_summon_assault_bot',
'spell_mimiron_summon_assault_bot_target',
'spell_mimiron_summon_fire_bot',
'spell_mimiron_summon_fire_bot_target',
'spell_mimiron_summon_flames_spread',
'spell_mimiron_summon_frost_bomb_target',
'spell_mimiron_summon_junk_bot',
'spell_mimiron_summon_junk_bot_target',
'spell_mimiron_weld',
'spell_mindless_abomination_explosion_fx_master',
'spell_monk_crackling_jade_lightning',
'spell_monk_glyph_of_mana_tea',
'spell_monk_mana_tea_stacks',
'spell_monk_serpents_zeal',
'spell_monk_teachings_of_the_monastery',
'spell_occuthar_eyes_of_occuthar_vehicle',
'spell_occuthar_focused_fire',
'spell_occuthar_occuthars_destruction',
'spell_oscillating_field',
'spell_pal_cleanse',
'spell_pal_consecration_area',
'spell_pal_glyph_of_holy_light',
'spell_pal_holy_radiance',
'spell_pal_holy_shock_damage',
'spell_pal_holy_shock_heal',
'spell_pal_item_healing_discount',
'spell_pal_lights_hammer_heal',
'spell_pal_templar_s_verdict',
'spell_pal_unbreakable_spirit',
'spell_pandaria_enchants',
'spell_paralyze_pinnacle',
'spell_pool_of_feed_dmg_aura',
'spell_ppm_hackfix',
'spell_pri_divine_hymn',
'spell_pri_glyph_of_holy_nova',
'spell_pri_hymn_of_hope',
'spell_pri_item_greater_heal_refund',
'spell_pri_leap_of_faith_effect_trigger',
'spell_pri_mana_burn',
'spell_pri_reflective_shield_trigger',
'spell_prince_taldaram_conjure_flame_sphere',
'spell_prince_taldaram_flame_sphere_summon',
'spell_putricide_ooze_summon',
'spell_quest29523_summon_living_air',
'spell_razelikh_teleport_group',
'spell_reversal_eff',
'spell_rimefang_icy_blast',
'spell_rog_assassasins_resolve',
'spell_rog_nightstalker',
'spell_rogue_rapture',
'spell_romoogg_call_for_help',
'spell_romoogg_chains_of_woe_tele',
'spell_romoogg_quake',
'spell_rotface_slime_spray',
'spell_sha_earthbind_totem',
'spell_sha_healing_rain_heal',
'spell_sha_item_lightning_shield',
'spell_sha_item_lightning_shield_trigger',
'spell_sha_item_mana_surge',
'spell_sha_item_t10_elemental_2p_bonus',
'spell_sha_lava_surge_proc',
'spell_sha_solar_beam',
'spell_sha_spirit_bite',
'spell_sha_spirit_wolf_leap',
'spell_shadow_pan_flare',
'spell_shadow_portal',
'spell_shadow_portal_rooms',
'spell_shadowfang_keep_haunting_spirits',
'spell_shango_tracks',
'spell_shredder_delivery',
'spell_sindragosa_frost_breath',
'spell_sindragosa_ice_tomb_dummy',
'spell_soo_shockwave_circle',
'spell_talon_king_ikiss_blink',
'spell_terrastra_grounded',
'spell_tharon_ja_clear_gift_of_tharon_ja',
'spell_the_lich_king_dark_hunger',
'spell_threatening_gaze',
'spell_trollgore_consume',
'spell_trollgore_corpse_explode',
'spell_tyrannus_rimefang_icy_blast',
'spell_uk_second_wind_proc',
'spell_ulduar_proximity_mines',
'spell_unseen_strike_aura',
'spell_veranus_summon',
'spell_warl_bane_of_doom',
'spell_warl_demon_soul',
'spell_warl_fel_synergy',
'spell_warl_glyph_of_nightmares',
'spell_warl_glyph_of_shadowflame',
'spell_warl_harvest_life',
'spell_warl_rain_of_fire_damage',
'spell_warl_shadow_ward',
'spell_warl_soul_link_dummy',
'spell_warl_soul_swap_dot_marker',
'spell_warl_soulburn_health_funnel',
'spell_warl_soulburn_remove',
'spell_warr_bloodbath_bleed',
'spell_warr_execute',
'spell_warr_glyph_of_gag_order',
'spell_warr_glyph_of_incite',
'spell_warr_glyph_of_sunder_armor',
'spell_warr_impaling_throws',
'spell_warr_second_wind_trigger',
'spell_warr_shields_visual',
'spell_warr_slam',
'spell_water_auras',
'spell_windsoul_totem_aura');
